language: php

php:
- 5.5
- 5.6
- 7
- hhvm

services: mysql

env:
- DB_HOST=127.0.0.1
- DB_DATABASE=livecms
- DB_USERNAME=root
- DB_PASSWORD=

before_script: 
- mysql -e 'create database livecms;'
- cp .env.example .env
- composer install --dev --prefer-source --no-interaction
- php artisan key:generate
- php artisan migrate --seed --force

scripts: phpunit